trial_series: audio-caption-retrieval

trial_base: "?"  # Output dir


# Configure ray-tune clusters
ray_conf:
    init_args:
        num_cpus: 1
        num_gpus: 1
        local_mode: False
        ignore_reinit_error: True
        _temp_dir: "?"

    search_space: { }
    search_algo: Null
    trial_scheduler: Null

    trial_stopper: TrialPlateauStopper
    stopper_args:
        metric: val_loss
        std: 0.01
        num_results: 10
        grace_period: 60
        metric_threshold: Null
        mode: min

    reporter: CLIReporter


# Configure training, validation, and evaluation data
data_conf:
    train_data: # training data
        dataset: "?"
        audio_data: development_audio_logmels.hdf5
        caption_data: development_captions.json
        text_vocab: vocab_info.pkl
        word_embeds: word2vec_embeds.pkl

    val_data: # validation data
        dataset: "?"
        audio_data: validation_audio_logmels.hdf5
        caption_data: validation_captions.json
        text_vocab: vocab_info.pkl
        word_embeds: word2vec_embeds.pkl

    eval_data: # evaluation data
        dataset: "?"
        audio_data: evaluation_audio_logmels.hdf5
        caption_data: evaluation_captions.json
        text_vocab: vocab_info.pkl
        word_embeds: word2vec_embeds.pkl

#    test_data: # testing data
#        dataset: "?"
#        audio_data: test_audio_logmels.hdf5
#        caption_data: test_captions.json
#        text_vocab: vocab_info.pkl
#        word_embeds: word2vec_embeds.pkl


# Configure hyper-parameters
param_conf:
    epochs: 150
    batch_size: 32
    model: CRNNWordModel
    criterion: TripletRankingLoss
    optimizer: AdamOptimizer
    lr_scheduler: ReduceLROnPlateau


# Model definitions
CRNNWordModel:
    name: CRNNWordModel

    audio_enc: # audio encoder branch
        in_dim: 64
        out_dim: 300
        up_sampling: linear

    text_enc: # text encoder branch
        word_enc: # word encoder
            init: prior # rand or prior
            embed_dim: 300
            trainable: False

    out_normd: L2


# Loss definitions
TripletRankingLoss:
    name: TripletRankingLoss
    args:
        margin: 1.0


# Optimizer definitions
AdamOptimizer:
    name: Adam
    args:
        lr: 0.001
        weight_decay: 0.0


# Learning rate scheduler definitions
ReduceLROnPlateau:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.1
        patience: 5
        threshold: 0.01
        threshold_mode: abs
